import array as myarr
arr=myarr.array('i',[0,1,2,3])
arr1=myarr.array('d',[0.1,1.1,2.1,3.1])
arr2=myarr.array('u',['a','b','c','d'])
print(arr)
print(type(arr))
print(len(arr))
print(arr1)
print(type(arr1))
print(len(arr1))
print(arr2)
print(type(arr2))
print(len(arr2))
for i in range(0,len(arr)):
    print(arr[i], end=' ')
print('\n')
for i in range(0,len(arr1)):
    print(arr1[i], end=' ')
print('\n')    
for i in range(0,len(arr2)):
    print(arr2[i], end=' ')
print('\n')
print(arr1[3])
x=list(range(1,50))
arr4=myarr.array('i', x)
print(arr4[25])
for i in range(0,len(arr4)):
   print(arr4[i],end=' ')
print('\n')   
arr.insert(0,7)
print(arr)   
arr.append(9)
print(arr)
for i in range(0,len(arr)):
    print(arr[i],end=' ')
print('\n')
arr.pop(0)
print(arr)
arr.remove(9)
print(arr)
arr[2]=4
print(arr)
arr5=arr.tolist()
arr5.sort(reverse=True)
print(arr5)
arr6=arr.index(1)
print(arr6)
print(arr[0:2])
